version: '3'

### Services
services:
  ### Web Server Container
  web:
    build: ./
    container_name: web
    restart: always
    ports:
      - "80:80"
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - ./var:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf
      - ./php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./logs/nginx:/var/log/nginx

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=firstlife142
      - MYSQL_DATABASE=admin_setscoped
      - MYSQL_USER=admin_setscopeu
      - MYSQL_PASSWORD=firstlife142
    networks:
      - deepscope

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mariadb:mariadb
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT= 1000G
    depends_on:
      - mariadb
    networks:
      - deepscope

networks:
  deepscope:
    # Use a custom driver
    driver: bridge